services:
  omnivault_app:
    container_name: omnivault_app
    build: ./
    environment:
      DATABASE_URL: "host=omnivault_db user=postgres password=postgres dbname=postgres sslmode=disable"
      # DATABASE_URL: "host=omnivault_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "5060:5060"
    depends_on:
      - omnivault_db

  omnivault_db:
    container_name: omnivault_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: omnivault_adminer
    ports:
      - "8080:8080"
    depends_on:
      - omnivault_db

networks:
  omnivault-network:
    driver: bridge

volumes:
  pgdata: {}
